### PR TITLE
support for zhaoxin cpu id

### PR DESCRIPTION
**Pull request by mormenthan**
lstopo will core dump when run on zhaoxin platform because of wrong cache information, add support for zhaoxin cpu id to fix it.

Signed-off-by: Jeff Zhao <jeffzhao@zhaoxin.com>

### CODE REVIEW

**Comment by bgoglin** [comment]
Hello.

The code looks good.

Can you add give information and/or links about the supported processor models since we are not familiar with them?

I see "CentaurHauls" and "Shanghai" in the vendor name in cpuid outputs, and google also talks about VIA. What are those vs Zhaoxin?

Also it would be good to have a test under tests/hwloc/x86/ for future regression testing. Please send the cpuid directory generated by hwloc-gather-cpuid, I'll create the test. If you cannot share that information yet, I'd still like to have it for my own private testing.

**Comment by mormenthan** [comment]
Thxs for your reply !

1. Here is some information of zhaoxin x86 cpu ids, which are compatible with Intel processors. You can visit http://en.zhaoxin.com/ for more information.
image

2.  VIA and Shanghai United Investment Co.,Ltd.(SUI) found Shanghai ZhaoXin, which is a fabless x86 CPU IC design company. ZhaoXin has issued ZX-C, ZX-D x86 processors, which have CentaurHalus and Shanghai CPU vendor ids. 

3.  I pull the latest hwloc code to run hwloc-gather-cpuid on Intel and ZhaoXin platform, it core dumped.
image

**Comment by bgoglin** [comment]
The hwloc-gather-cpuid assert failure should disappear if you remove --enable-debug at configure time. 

But I'd need the full textual output with debug enabled to debug the actual issue.

**Comment by bgoglin** [comment]
The segfault should be fixed with https://github.com/bgoglin/hwloc/commit/8ac71cfbc9be45ca2840ce104e40adad5927efdb

**Comment by mormenthan** [comment]
Thxs for comment.

I already run hwloc-gather-cpuid on ZhaoXin platform, and the attachments are CentaurHauls and Shanghai cpuid directory.
1.  [centahauls-cpuid.tar.gz](https://github.com/open-mpi/hwloc/files/1592964/centahauls-cpuid.tar.gz)
2.  [shanghai-cpuid.tar.gz](https://github.com/open-mpi/hwloc/files/1592966/shanghai-cpuid.tar.gz)

**Comment by bgoglin** [comment]
Thanks. I'll push your code and add your cpuid dumps to regression testing inside the repo.

So (just to be sure) can you confirm that the output is correct: both CPUs have 8 cores with 32kB L1i and 32kB L1d each. The Shanghai CPU has a 2MB shared L2 between 8 cores. The CentauHauls has two 4MB L2 shared by 4 cores.

**Comment by mormenthan** [comment]
I'm sorry for late response because of on holiday.

**Yes, I'm sure the information is correct.**

**Comment by bgoglin** [comment]
Pushed to git master (commit 142f3e4451f7f02e08018bcb36479e42e65cd255) and v1.11 stable branch (a55ebbac5a141291db67ff949ac1479a978601dd).
This will be in the upcoming 2.0 and 1.11.9 releases.
Current snapshot tarballs are available from https://ci.inria.fr/hwloc/job/master-0-tarball/ and https://ci.inria.fr/hwloc/job/v1.11-0-tarball/
Thanks!

**Comment by mormenthan** [comment]
Thank you very much.

**Pull request closed without merging**
