### PR TITLE
Support for clang-cl on windows

### PR DESCRIPTION
**Pull request by isuruf**
I'm using a simple wrapper around clang-cl for making the configure script work.

There are few things that I need to change that I need help with,

1. Line https://github.com/open-mpi/hwloc/blob/f3ba1fea561c23c5afd1c3856818506fced4c96f/hwloc/Makefile.am#L170 needs to be changed as clang-cl doesn't understand `--output-def` and libtool creates it. It needs to be changed to `-Xlinker -def:.libs/libhwloc.def` depending on whether we are using clang-cl or gnu tools like mingw and cygwin.

2. strcasecmp check goes through with a warning of implicit declaration.

### CODE REVIEW

**Comment by bgoglin** [comment]
What is your wrapper? Our windows support isn't in very good shape. We basically try to support MinGW and MSVC, only versions we have in CI VMs, and I don't know if that's very useful and/or enough. So feedback about what you are doing with clang and why might be useful. We might even add a clang Windows regression testing if it works well.

Regarding the fix of pid_t in one example, I don't think it's appropriate. That test won't work on Windows anyway (there's a FIXME in there). If you're fixing a warning, I'd rather keep the warning to make it clear the code isn't ready for Windows. If you're fixing a build failure, I'd rather disable that test on Windows.

You should use #ifdef HAVE_UNISTD_H for avoiding #include <unistd.h> just like we do everywhere else. We don't do it in tests because we only build these on Windows uisng MinGW (which seems to provide unistd.h) but we can certainly add #ifdef there.

Missing definitions such as S_IRWXU should go to include/private/misc.h (look for HWLOC_WIN_SYS).

Regarding -Xlinker, any idea how to detect this? Should we detection the model of compiler during configure? Have you seen any other project support both cases like this?

**Comment by isuruf** [comment]
Thanks for your detailed reply and interest.

> What is your wrapper? Our windows support isn't in very good shape. We basically try to support MinGW and MSVC, only versions we have in CI VMs, and I don't know if that's very useful and/or enough. So feedback about what you are doing with clang and why might be useful. We might even add a clang Windows regression testing if it works well.

I wanted to build hwloc with MSVC or clang-cl so that it is ABI compatible with MSVC C runtime. I first tried the Visual Studio solution files which didn't work for me with VS2017. (Also tests were not built with it). Here's a simple script that I use, https://github.com/conda-forge/libhwloc-feedstock/blob/58c8b31a5dc2ccb58354e11f61bcc73469a4e900/recipe/cl_wrapper.sh so that I can use autotools with it.

clang-cl has the same interface as MSVC's cl and the libraries built are ABI compatible with libraries built with MSVC's cl.

> Regarding the fix of pid_t in one example, I don't think it's appropriate. That test won't work on Windows anyway (there's a FIXME in there). If you're fixing a warning, I'd rather keep the warning to make it clear the code isn't ready for Windows. If you're fixing a build failure, I'd rather disable that test on Windows.

It's a build failure.

> You should use #ifdef HAVE_UNISTD_H for avoiding #include <unistd.h> just like we do everywhere else. We don't do it in tests because we only build these on Windows uisng MinGW (which seems to provide unistd.h) but we can certainly add #ifdef there.

Will do

> Regarding -Xlinker, any idea how to detect this? Should we detection the model of compiler during configure? Have you seen any other project support both cases like this?

I haven't seen the need for `--output-def`. That whole line can be dropped in the case of clang-cl (and I'm pretty sure, MinGW too, but that means libhwloc.def is not installed, but I don't see the need to install the .def file) . configure scripts checks for dependency style of the compiler and clang-cl gives `msvc7` while MinGW gives `gcc3`. This can be used for checking, but I'm not sure how to access this variable `CCDEPMODE` in hwloc/Makefile.am

**Comment by bgoglin** [comment]
Given that there's not a single comment in your wrapper, can you explain what it does?

There's another good thing about using clang on Windows, it's C99 compliant. MSVC is really a pain on that side. However I was rather thinking of using clang inside a VS solution (but didn't try). If our VS solution isn't compatible with recent VS, it's really annoying to maintain...

@sthibaul Do you remember why you used that def file for Windows 9 years ago? :)

**Comment by sthibaul** [comment]
The .def file is needed to build the .lib file using MS' lib.exe. If clang already builds the .lib file itself, there is no need for the intermediate .def file.

**Comment by bgoglin** [comment]
I just pushed 3 patches that take care of unistd.h, pid_t and S_IRWXU

For strcasecmp, AC_INCLUDES_DEFAULT already includes strings.h, and it should be enabled because we have AC_CHECK_HEADERS([strings.h]) above in the configure. Check your config.log to find out whether strings.h is found and HAVE_STRINGS_H is defined for the strcasecmp test.

For diff CR, I am looking for a smaller way to fix it.

**Comment by isuruf** [comment]
> Given that there's not a single comment in your wrapper, can you explain what it does?

Will do tonight. (It was inspired by https://github.com/swig/cccl, but since it didn't work for me, I wrote one myself.)

> I just pushed 3 patches that take care of unistd.h, pid_t and S_IRWXU

Thanks for doing this.

> For strcasecmp, AC_INCLUDES_DEFAULT already includes strings.h, and it should be enabled because we have AC_CHECK_HEADERS([strings.h]) above in the configure. Check your config.log to find out whether strings.h is found and HAVE_STRINGS_H is defined for the strcasecmp test.

I looked into the config.log. "strings.h" is not found and `HAVE_STRINGS_H` is not defined because it is not available on windows/msvc. clang-cl choose to give a warning saying strcasecmp is implicitly defined instead of erroring out and the configure script thinks that strcasecmp is defined. Maybe the check for strcasecmp should happen only if strings.h is found ?

**Comment by isuruf** [comment]
The compiler wrapper I'm using extract out all the link arguments and converts them to link.exe format and adds them at the end after `-link`
`-lgdi32 -> gdi32.lib`
`-Lfolder -> -libpath:folder`
`-Wl,-DLL,IMPLIB:hwloc.lib -> -DLL IMPLIB:hwloc.lib`

So, something like `clang-cl asd.obj -Lfolder -Wl,-DLL,IMPLIB:hwloc.lib -lgdi32` becomes
`clang-cl asd.obj -link gdi32.lib -libpath:folder -DLL IMPLIB:hwloc.lib`

**Comment by isuruf** [comment]
> The .def file is needed to build the .lib file using MS' lib.exe. If clang already builds the .lib file itself, there is no need for the intermediate .def file.

libtool generates `.def` file for clang-cl and then clang-cl uses MS' lib.exe to create the .lib file. I imagine this would be the same for a MinGW build, but I don't know your exact setup. Can you try removing that line with a newer libtool?

**Comment by bgoglin** [comment]
Indeed after installing libtool in my MSYS and removing all the Xlinker and mslib stuff from the Makefile, I get a working install. The install dir contains:
```
bin/:                                                                           
-rwxr-xr-x 1 ci None  487255 24 sept. 21:41 hwloc-annotate.exe                  
[...]
-rwxr-xr-x 1 ci None  401594 24 sept. 21:41 hwloc-patch.exe                     
-rwxr-xr-x 1 ci None 1452511 24 sept. 21:41 libhwloc-0.dll                      
-rwxr-xr-x 1 ci None  788655 24 sept. 21:41 lstopo-no-graphics.exe              
-rwxr-xr-x 1 ci None  835268 24 sept. 21:41 lstopo-win.exe                      
-rwxr-xr-x 1 ci None  835268 24 sept. 21:41 lstopo.exe                          
                                                                                
lib/:                                                                           
-rw-r--r-- 1 ci None 1299780 24 sept. 21:41 libhwloc.a                          
-rw-r--r-- 1 ci None  158616 24 sept. 21:41 libhwloc.dll.a                      
-rw-r--r-- 1 ci None    1046 24 sept. 21:41 libhwloc.la                         
drwxr-xr-x 1 ci None       0 24 sept. 21:41 pkgconfig                           
```
(The -0 suffix comes from this tarball not being an official release).

A normal hwloc release would have these additional files:
```
-rw-r--r-- 1 ci None    7995  2 sept. 14:59 libhwloc.def                        
-rw-r--r-- 1 ci None   35279  2 sept. 14:59 libhwloc.exp                        
-rw-r--r-- 1 ci None   59608  2 sept. 14:59 libhwloc.lib
```
Are they needed for external programs that would want to link to libhwloc?

**Comment by sthibaul** [comment]
> Are they needed for external programs that would want to link to libhwloc?

Yes, MSVC wants the .lib file

**Comment by bgoglin** [comment]
I pushed that fix too.
Now for diff CR/LF, we use -w in some tests because of CR/LF issues according to git log. But we don't use it in all tests. Can you check whether your added diff options is needed everywhere or only in tests that don't already have -w?

**Comment by isuruf** [comment]
You are right. They are needed only in tests that don't already have -w

**Comment by bgoglin** [comment]
Hopefully diff CR/LF will be fixed with https://github.com/bgoglin/hwloc/commit/a4f6d41d544259acb12867ef7400d54c734fcb00 (currently under testing in my clone)

**Comment by bgoglin** [comment]
Thinking more about the Xlinker issue, I think the proper solution would be to have your wrapper replace -Xlinker --output-def -Xlinker .libs/libhwloc.def with -Xlinker -def:.libs/libhwloc.def
Can't you dequeue all arguments behind a -Xlinker, than apply a regexp to replace "--output-def X" with -def:X and then requeue the result behind one -Xlinker per word?

Did you have a chance to test the diff -u -w patch?

**Comment by isuruf** [comment]
I did use the diff -u -w patch and it works. There's an issue with `S_IRWXU` because `private/misc.h` header is not included `hwloc_backends.c` test file

**Comment by bgoglin** [comment]
Thanks, I pushed the diff -w patch to git master and v2.0, and I pushed the addition of #include <private/misc.h> in hwloc_backends.c

**Comment by isuruf** [comment]
I checked latest master with https://github.com/bgoglin/hwloc/commit/ace7c213d7cf6ce0f293b86126131d5502e12a1a and all tests passed except for x86 tests which I've disabled when building. Thanks for all your help.

**Pull request closed without merging**
