### PR TITLE
Update libhwloc.vcxproj to support static linking

### PR DESCRIPTION
**Pull request by fj40bryan**
Fix Windows static linking for libhwloc

Signed-off-by: Bryan Hunt <bryanjhunt@msn.com>

### CODE REVIEW

**Comment by bgoglin** [comment]
Merged, thanks!

**Comment by fj40bryan** [comment]
Thank you!

Sent from my iPhone

On Sep 1, 2020, at 12:52 AM, Brice Goglin <notifications@github.com> wrote:

﻿

Merged, thanks!

**Comment by fj40bryan** [comment]
Hi @bgoglin, is there a link to a release schedule? Im not in a rush, but just curious.

**Comment by bgoglin** [comment]
Hello @fj40bryan 
There's no clear release schedule. I'd like to release 2.3 before end of September but I usually fail to meet deadlines :/

**Comment by bgoglin** [comment]
@fj40bryan I just released 2.3.0rc1. Unless some bugs appear, it means 2.3.0 final within a week.

**Pull request merged**
